#!/bin/bash
cd "$HOME"

# Would probably like to add yadm path here
export PATH=$HOME/.local/bin:$PATH

echo "Init submodules"
yadm submodule update --recursive --init


ln -s $HOME/zsh_custom/themes/spaceship-prompt/spaceship.zsh-theme $HOME/zsh_custom/themes/spaceship.zsh-theme


echo "Continue installs"
source $HOME/.scripts/install_continue.sh
