#!/bin/bash
cd "$HOME"

# Would probably like to add yadm path here
export PATH=$HOME/.local/bin:$PATH

echo "Init submodules"
yadm submodule update --recursive --init


echo "Continue installs"
source $HOME/.scripts/install_continue.sh
